trigger:
- none


variables:

- name: ContainerRegistry
  value: akscontaineregistrydemo.azurecr.io

- name: imageRepository
  value: app1nginxaks

- name: tag
  value: $(Build.SourceVersion)

- name: vmImageName
  value: ubuntu-latest


steps:


- checkout: self


- script: |

    sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 \
    -O /usr/local/bin/yq

    sudo chmod +x /usr/local/bin/yq


    cd app1


    yq -i '
    .spec.template.spec.containers[0].image =
    "$(ContainerRegistry)/$(imageRepository):$(tag)"
    ' deployment.yml


    git config user.email "azurepipeline@gmail.com"

    git config user.name "Azure Pipeline"


    git add deployment.yml


    git commit -m "Update image $(tag) in deployment.yml"


    git push origin main


  displayName: Update GitOps Manifest