apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: app1-dev
  namespace: argocd

spec:
  source:
    repoURL: https://github.com/nishadZC/gitops-repo.git
    path: charts/app1

    helm:
      valueFiles:
      - values-qa.yaml

  destination:
    namespace: qa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true