apiVersion: apps/v1
kind: Deployment

metadata:
  name: app1nginxaks
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: app1nginxaks

  template:
    metadata:
      labels:
        app: app1nginxaks

    spec:
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
      - name: app1nginxaks
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 80