apiVersion: v1
kind: Service

metadata:
  name: app1nginxaks
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: app1nginxaks

  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80

  type: {{ .Values.service.type }}